version: "3"
services:
  app:
    image: semear
    build:
      context: .
    ports:
      - 5000:80
      - 5001:443
    networks:
      - semear-network
  #command: ["dotnet", "MyWebApp.dll"]
networks:
  nibo-network:
    driver: bridge
