version: 0.2
phases:
    install:
        runtime-versions:
            dotnet: 3.1
    pre_build:
        commands:
            - echo Restore started on `date`
            - dotnet retore ./MyWebApp/MyWebApp.csproj
    build:
        commands:
            - echo Build started on `date`
            - dotnet publish -c release -o ./MyWebApp/MyWebApp.csproj